### ISSUE TITLE
Error filtering log events if Lambda function is aliased in APIGW

### ISSUE THREAD

**Issue by elevenE** [rpgreen/apilogs#1]
Hi,

If the Lambda integration in APIGW points to an aliased Lambda function, the call to `filter_log_events` fails because the regex doesn't match. Might need to strip the the alias before calling `filter_log_events`.

```
C:\Users\me\Downloads\apilogs (master)
λ python -m apilogs.bin get --api-id xyz123 --stage live --watch --profile dev
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\Users\me\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\me\Downloads\apilogs\apilogs\core.py", line 229, in generator
    response = self.client.filter_log_events(**kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python35-32\lib\site-packages\botocore\client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python35-32\lib\site-packages\botocore\client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterException) when calling the FilterLogEvents operation: 1 validation error detected: Value '/aws/lambda/IDM_ChangeEmailAddress:live' at 'logGroupName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]+

```

**Comment by innovia** [comment]
im getting the same error,
i printed the lambda group it fails on

python -m apilogs.bin get -a xyz123 --stage dev  
lambda_group: /aws/lambda/my-function:${stageVariables.functionAlias}

an easy fix is the following 
add this to line 156 on apilogs/core.py

``` python
  def list_lambda_logs(allevents, kwargs):
            # add events from lambda function streams
            fxns = self.get_lambda_function_names(self.api_id, self.stage)
            for fxn in fxns:
                lambda_group = "/aws/lambda/" + fxn
                lambda_group = lambda_group.split(':')[0]
```

**Comment by rpgreen** [comment]
Thanks - pushed
